theme: jekyll-theme-midnight
permalink: /:title/
markdown: kramdown
date_format: "%B %-d, %Y %I:%M %p %Z"
title: ToxBlog
description: Welcome to my big-ass fucking blog!!! Read about my borin’ life here!!
timezone: Europe/London
