theme: jekyll-theme-midnight
permalink: /:title/
markdown: kramdown
date_format: "%B %-d, %Y %I:%M %p %Z"
title: UNDERTOW
description: A probably evil blog
timezone: Europe/London
backgroundurl: https://images.unsplash.com/photo-1585575141647-c2c436949374?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Ymx1ZSUyMHNwYWNlfGVufDB8fDB8fA%3D%3D
